name: "Dispatch downstream flake lock updates"

on:
  pull_request:
    types: [closed]

jobs:
  dispatch:
    if: >-
      github.event.pull_request.merged == true &&
      contains(github.event.pull_request.labels.*.name, 'automated')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo:
          - weltenwort/dot-nix-darwin
          - weltenwort/dot-nix-dev
    steps:
      - name: Dispatch to ${{ matrix.repo }}
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
          repository: ${{ matrix.repo }}
          event-type: update-shared-flake-lock
